export enum UserEvent {
  APP_OPEN = 'APP_OPEN',
  EXTENSION_INSTALL = 'EXTENSION_INSTALL',
  EXTENSION_UPDATE = 'EXTENSION_UPDATE',
  PROMPT_SAVE = 'PROMPT_SAVE',
  PROMPT_UNSAVE = 'PROMPT_UNSAVE',
  MESSAGE_SENT = 'MESSAGE_SENT',
  EXTENSION_UNINSTALL = 'EXTENSION_UNINSTALL',
  TOOLBOX_ACTION = 'TOOLBOX_ACTION',
  TOOLBOX_MENU_CLICK = 'TOOLBOX_MENU_CLICK',
  TOOLBOX_WEBSITE_TOGGLE = 'TOOLBOX_WEBSITE_TOGGLE',
}

export enum OpenAppSource {
  TOPBAR = 'topbar',
  CONTEXT_MENU = 'context-menu',
  FLOATING_WIDGET = 'floating-widget',
  SHORTCUT = 'shortcut',
  TOOLBAR = 'toolbar',
}
